# Generated by Django 3.2.18 on 2023-06-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230602_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='mesurement_unit',
            new_name='measurement_unit',
        ),
    ]
